// Danh sách 34 tỉnh/thành Việt Nam theo Nghị quyết 202/2025/QH15 (áp dụng từ 01/07/2025)
export const PROVINCES: string[] = [
  'Tuyên Quang',
  'Cao Bằng',
  'Lai Châu',
  'Lào Cai',
  'Thái Nguyên',
  'Điện Biên',
  'Lạng Sơn',
  'Sơn La',
  'Phú Thọ',
  'Bắc Ninh',
  'Quảng Ninh',
  'TP. Hà Nội',
  'TP. Hải Phòng',
  'Hưng Yên',
  'Ninh Bình',
  'Thanh Hóa',
  'Nghệ An',
  'Hà Tĩnh',
  'Quảng Trị',
  'TP. Huế',
  'TP. Đà Nẵng',
  'Quảng Ngãi',
  'Gia Lai',
  'Đắk Lắk',
  'Khánh Hòa',
  'Lâm Đồng',
  'Đồng Nai',
  'Tây Ninh',
  'TP. Hồ Chí Minh',
  'Đồng Tháp',
  'An Giang',
  'Vĩnh Long',
  'TP. Cần Thơ',
  'Cà Mau',
];
